Blog/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Blog.Models;
using Blog.Extensions;
using Blog.BLL.Services;
using Blog.BLL.Models;
using Blog.BLL.Response;

namespace Blog.Controllers
{
    // Класс контроллера, реализующий основные CRUD-операции статьи
    public class ArticleController : Controller
    {
        private readonly ILogger<ArticleController> _logger;
        private IMapper _mapper;
        private IArticleService _articleService;

        public ArticleController(IMapper mapper, IArticleService articleService, ILogger<ArticleController> logger)
        {
            _logger = logger;
            _mapper = mapper;
            _articleService = articleService;
        }

        /// <summary>
        /// Запрос представления добавления статьи
        /// </summary>
        /// <returns> View добавления статьи </returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AddArticle()
        {
            ArticleEditViewModel article = new ArticleEditViewModel();
            var tags = await Task.FromResult(_articleService.GetAllTags());
            article.CheckTags = tags.Select(t => new CheckTagViewModel { Id = t.Id, Title = t.Title, Checked = false }).ToList();

            return View(article);
        }

        /// <summary>
        /// Добавление статьи
        /// </summary>
        /// <param name="newArticle"> ViewModel статьи </param>
        /// <returns> Возвращает представление просмотра статьи, в противном случае представление её добавления </returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddArticle(ArticleEditViewModel newArticle)
        {
            if (ModelState.IsValid)
            {
                var article = _mapper.Map<ArticleDomain>(newArticle);

                article.UserId = User.Identity.GeUsertId();

                EntityBaseResponse<ArticleDomain> result = await _articleService.Add(article);

                if (result.Success)
                {
                    _logger.LogInformation($"Пользователь {User.Identity.Name} добавил статью {article.Title}.");
                    return RedirectToAction("ViewArticle", new { result.Entity.Id });
                }
                else
                {
                    View(newArticle);
                }
            }
            else
            {
                _logger.LogInformation(ModelState.GetAllError());
            }

            return View(newArticle);
        }

        /// <summary>
        /// Получение представления редактирования статьи
        /// </summary>
        /// <param name="id"> Идентификатор редактируемой статьи </param>
        /// <returns> Вовзращает представлене редактирования статьи </returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditArticle(int id)
        {
            EntityBaseResponse<ArticleDomain> article = await _articleService.Get(id);
            if (article.Success)
            {
                List<TagDomain> allTags = _articleService.GetAllTags().ToList();
                ArticleEditViewModel articleEdit = _mapper.Map<ArticleEditViewModel>(article.Entity);

                articleEdit.CheckTags = allTags.Select(t => new CheckTagViewModel
                {
                    Id = t.Id,
                    Title = t.Title,
                    Checked = article.Entity.Tags.Any(pt => pt.Id == t.Id)
                }).ToList();

                return View(articleEdit);
            }
            else
            {
                return View("NotFound");
            }
        }

        /// <summary>
        /// Редактирование статьи
        /// </summary>
        /// <param name="model"> ViewModel редактирования статьи </param>
        /// <returns> View редактирования статьи </returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditArticle(int id, ArticleEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var article = _mapper.Map<ArticleDomain>(model);
                await _articleService.Update(article);
                _logger.LogInformation($"Пользователь {User.Identity.Name} отредактировал статью {article.Title}");

                return RedirectToAction("ViewArticle", new { id });
            }
            else
            {
                _logger.LogInformation(ModelState.GetAllError());
            }

            return View(model);

        }

        /// <summary>
        /// Удаление статьи
        /// </summary>
        /// <param name="id"> Идентификатор статьи </param>
        /// <returns> View списка статей </returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            EntityBaseResponse<ArticleDomain> article = await _articleService.Get(id);
            if (!article.Success)
            {
                return View("NotFound");
            }

            article = await _articleService.Delete(article.Entity);
            if (!article.Success)
            {
                _logger.LogInformation($"Пользователь {User.Identity.Name} удалил статью {article.Entity.Title}.");
            }

            return RedirectToAction("ArticleList");
        }

        /// <summary>
        /// Получение списка статей
        /// </summary>
        /// <returns> View списка статей </returns>
        [HttpGet]
        public async Task<IActionResult> ArticleList()
        {
            var articleList = await Task.FromResult(_articleService.GetAll());
            List<ArticleViewModel> resultArticleList = _mapper.Map<List<ArticleViewModel>>(articleList.Entity);

            return View(resultArticleList);
        }

        /// <summary>
        /// Получить статью по ID
        /// </summary>
        /// <param name="id"> Идентификатор статьи </param>
        /// <returns> View статьи </returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> ViewArticle(int id)
        {
            var articleResponse = await _articleService.Get(id);

            if (!articleResponse.Success)
            {
                _logger.LogInformation(articleResponse.Message);

                return View("NotFound");
            }

            return View(_mapper.Map<ArticleViewModel>(articleResponse.Entity));
        }
    }
}

Blog/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Blog.Models;
using Blog.Extensions;
using Blog.BLL.Services;
using Blog.BLL.Models;
using Blog.BLL.Response;

namespace Blog.Controllers
{
    // Класс контроллера, реализующий основные CRUD-операции роли
    public class RoleController : Controller
    {
        private readonly ILogger<RoleController> _logger;
        private IMapper _mapper;
        private IRoleService _roleService;

        public RoleController(IMapper mapper, IRoleService roleService, ILogger<RoleController> logger)
        {
            _mapper = mapper;
            _roleService = roleService;
            _logger = logger;
        }

        /// <summary>
        /// Запрос представления добавления роли
        /// </summary>
        /// <returns> View добавления роли </returns>
        [Authorize(Roles = "Aдминистратор")]
        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        /// <summary>
        /// Добавление роли
        /// </summary>
        /// <param name="newRole"> Модель новой роли </param>
        /// <returns> View списка ролей </returns>
        [HttpPost]
        [Authorize(Roles = "Aдминистратор")]
        public async Task<IActionResult> AddRole(RoleEditViewModel newRole)
        {
            if (ModelState.IsValid)
            {
                var role = _mapper.Map<RoleDomain>(newRole);

                EntityBaseResponse<RoleDomain> result = await _roleService.Add(role);
                if (result.Success)
                {
                    _logger.LogInformation($"Пользователь {User.Identity.Name} добавил роль {role.Description}.");
                    return RedirectToAction("RoleList");
                }
            }
            else
            {
                _logger.LogInformation(ModelState.GetAllError());
            }

            return View(newRole);
        }

        /// <summary>
        /// Запрос представления редактирования роли
        /// </summary>
        /// <param name="id"> Идентификатор роли </param>
        /// <returns> View редактирования роли </returns>
        [Authorize(Roles = "Aдминистратор")]
        [HttpGet]
        public async Task<IActionResult> EditRole(int id)
        {
            EntityBaseResponse<RoleDomain> role = await _roleService.Get(id);
            if (role.Success)
            {
                RoleEditViewModel roleEdit = _mapper.Map<RoleEditViewModel>(role.Entity);
                return View(roleEdit);
            }
            else
            {
                return View("NotFound");
            }
        }

        /// <summary>
        /// Редактирование роли
        /// </summary>
        /// <param name="model"> ViewModel редактирования роли </param>
        /// <returns> View редактирования роли </returns>
        [Authorize(Roles = "Aдминистратор")]
        [HttpPost]
        public async Task<IActionResult> EditRole(RoleEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = _mapper.Map<RoleDomain>(model);
                await _roleService.Update(role);
                _logger.LogInformation($"Пользователь {User.Identity.Name} отредактировал роль id = {role.Id} {role.Description}");

                return RedirectToAction("RoleList");
            }
            else
            {
                _logger.LogInformation(ModelState.GetAllError());
            }

            return View(model);
        }

        /// <summary>
        /// Удаление роли
        /// </summary>
        /// <param name="id"> Идентификатор роли </param>
        /// <returns> View списка ролей </returns>
        [Authorize(Roles = "Aдминистратор")]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            EntityBaseResponse<RoleDomain> role = await _roleService.Get(id);
            if (!role.Success)
            {
                return View("NotFound");
            }

            role = await _roleService.Delete(role.Entity);
            if (role.Success)
            {
                _logger.LogInformation($"Пользователь {User.Identity.Name} удалил роль {role.Entity.Description}.");
            }

            return RedirectToAction("RoleList");
        }

        /// <summary>
        /// Получение View списка ролей
        /// </summary>
        /// <returns> View списка ролей </returns>
        [Authorize(Roles = "Aдминистратор")]
        [HttpGet]
        public async Task<IActionResult> RoleList()
        {
            var roleList = await Task.FromResult(_roleService.GetAll());
            List<RoleViewModel> resultRoleList = _mapper.Map<List<RoleViewModel>>(roleList.Entity);

            return View(resultRoleList);
        }

        /// <summary>
        /// Получение роли по ID
        /// </summary>
        /// <param name="id"> Идентификатор роли </param>
        /// <returns> View роли </returns>
        [Authorize(Roles = "Aдминистратор")]
        [HttpGet]
        public async Task<IActionResult> ViewRole(int id)
        {

            var roleResponse = await _roleService.Get(id);
            if (!roleResponse.Success)
            {
                _logger.LogInformation($"Роль с Id = {id} не найдена.");
                return View("NotFound");
            }

            return View(_mapper.Map<RoleViewModel>(roleResponse.Entity));

        }
    }
}

Blog/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Blog.Models;
using Blog.Extensions;
using Blog.BLL.Services;
using Blog.BLL.Models;
using Blog.BLL.Response;

namespace Blog.Controllers
{
    // Класс контроллера, реализующий основные CRUD-операции тега
    public class TagController : Controller
    {
        private readonly ILogger<TagController> _logger;
        private IMapper _mapper;
        private ITagService _tagService;

        public TagController(IMapper mapper, ITagService tagService, ILogger<TagController> logger)
        {
            _logger = logger;
            _mapper = mapper;
            _tagService = tagService;
        }

        /// <summary>
        /// Запрос представления добавления тега
        /// </summary>
        /// <returns> View добавления тега </returns>
        [Authorize]
        [Authorize]
        [HttpGet]
        public IActionResult AddTag()
        {
            return View();
        }

        /// <summary>
        /// Добавление тега
        /// </summary>
        /// <returns> View добавления тега </returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddTag(TagEditViewModel newTag)
        {
            if (ModelState.IsValid)
            {
                var tag = _mapper.Map<TagDomain>(newTag);

                EntityBaseResponse<TagDomain> result = await _tagService.Add(tag);
                if (result.Success)
                {
                    _logger.LogInformation($"Пользователь {User.Identity.Name} добавил тэг {tag.Title}.");
                    return RedirectToAction("TagList");
                }
            }
            else
            {
                _logger.LogInformation(ModelState.GetAllError());
            }

            return View(newTag);
        }

        /// <summary>
        /// Запрос представления редактирования тега
        /// </summary>
        /// <param name="id"> Идентификатор тега </param>
        /// <returns> View редактирования тега returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditTag(int id)
        {
            EntityBaseResponse<TagDomain> tag = await _tagService.Get(id);
            if (tag.Success)
            {
                TagEditViewModel tagEdit = _mapper.Map<TagEditViewModel>(tag.Entity);
                return View(tagEdit);
            }
            else
            {
                return View("NotFound");
            }
        }

        /// <summary>
        /// Редактирование тега
        /// </summary>
        /// <param name="model"> ViewModel редактирования тега </param>
        /// <returns> View редактирования тега </returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditTag(TagEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tag = _mapper.Map<TagDomain>(model);
                await _tagService.Update(tag);
                _logger.LogInformation($"Пользователь {User.Identity.Name} отредактировал тэг id = {tag.Id} {tag.Title}");

                return RedirectToAction("TagList");
            }
            else
            {
                _logger.LogInformation(ModelState.GetAllError());
            }

            return View(model);
        }

        /// <summary>
        /// Удаление тега
        /// </summary>
        /// <param name="id"> Идентификатор тега </param>
        /// <returns> View списка тегов</returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            EntityBaseResponse<TagDomain> tag = await _tagService.Get(id);
            if (!tag.Success)
            {
                return View("NotFound");
            }

            tag = await _tagService.Delete(tag.Entity);
            if (tag.Success)
            {
                _logger.LogInformation($"Пользователь {User.Identity.Name} удалил тэг {tag.Entity.Title}.");

            }

            return RedirectToAction("TagList");
        }

        /// <summary>
        /// Получение View списка тегов
        /// </summary>
        /// <returns> View списка тегов </returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> TagList()
        {
            var tagList = await Task.FromResult(_tagService.GetAll());
            List<TagViewModel> resultTagList = _mapper.Map<List<TagViewModel>>(tagList.Entity);

            return View(resultTagList);

        }

        /// <summary>
        /// Получение тега по ID
        /// </summary>
        /// <param name="id"> Идентификатор тега </param>
        /// <returns> View тега </returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ViewTag(int id)
        {
            var tagResponse = await _tagService.Get(id);

            if (!tagResponse.Success)
            {
                _logger.LogInformation(tagResponse.Message);
                return View("NotFound");
            }

            return View(_mapper.Map<TagViewModel>(tagResponse.Entity));
        }
    }
}

Blog/Views/Shared/Forbidden.cshtml
@{
    ViewData["Title"] = "Ошибка 403";
}

<h2>ERROR 403 (Доступ запрещён)</h2>

Blog/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Ошибка 404";
}

<h2>ERROR 404 (Ресурс не найден)</h2>

Blog/Views/Shared/_AddComment.cshtml
@model CommentEditViewModel

<div class="row">
    <div class="col-md-12">
        <form method="post" asp-controller="Comment" asp-action="AddComment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="ArticleId" class="form-control" type="hidden"/>

            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" type="text" class="form-control" placeholder="Ваш комментарий"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Оставить комментарий" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Blog/Views/Shared/_ArticleCommentList.cshtml
@model IEnumerable<Blog.Models.CommentViewModel>

<h4>Комментарии</h4>

@foreach (var comment in Model) {
    <div class="form-group">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    Комментарий к статье: <a asp-controller="Article" asp-action="ViewArticle" asp-route-id="@comment.Article.Id">@comment.Article.Title</a>
                </h5>
                <p class="card-text">@comment.Content</p>
            </div>
        </div>
        <p class="text-right">
            <span class="badge bg-success text-light">@comment.Author</span>
        </p>
    </div>
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>БLОГ - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Article" asp-action="ArticleList">БLОГ</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if(User.IsInRole("Aдминистратор")) 
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Comment" asp-action="CommentList">Комментарии</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="TagList">Теги</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserList">Пользователи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="RoleList">Роли</a>
                            </li>
                        </ul>
                    }
                </div>

                @if(User.Identity.IsAuthenticated) 
                {
                    <a class="breadcrumb" asp-area="" asp-controller="User" asp-action="Logout">Выход</a>
                }
                else 
                {
                    <a class="breadcrumb" asp-area="" asp-controller="User" asp-action="Authenticate">Войти</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023. БLОГ
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>